export PATH=/Users/mlennon/Library/Python/2.7/bin/:$PATH
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
alias ll='ls -la'
alias gst='git status'
alias dc='docker-compose'

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export FZF_DEFAULT_COMMAND='ag --ignore node_modules --nocolor -g ""'

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
